apiVersion: v2
name: cp4data-operator
description: Deployment of Cloud Pak for Data oeprators
type: application
version: 0.1.1
appVersion: "1.0"
dependencies:
  - name: cp4data-operator
    version: 0.1.1
    repository: https://chechuironman.github.io/helm-repo/