apiVersion: external-secrets.io/v1alpha1
kind: SecretStore
metadata:
  name: ibm-secret-manager
spec:
  provider:
    ibm:
      serviceUrl: "https://9317c2fa-de61-4d3f-bde5-238e1a8f9740.us-south.secrets-manager.appdomain.cloud"
      auth:
        secretRef:
          secretApiKeySecretRef:
            name: ibm-secret
            key: apiKey