apiVersion: v2
name: mq-instance
description: Deployment of MQ instance
type: application
version: 0.1.14
appVersion: "0.1.14"
dependencies:
  - name: mq-instance
    version: 0.1.14
    repository: https://chechuironman.github.io/helm-repo/


