apiVersion: v2
name: external-secret-operator
description: A Helm chart for Kubernetes
type: application
version: 0.1.0
appVersion: "1.0"
dependencies:
  - name: external-secrets
    version: 0.3.5 
    repository: https://charts.external-secrets.io