global: {}

ibm-common-services:
  subscriptions:
    subscription:
      channel: v3
      config:
        resources: {}
      installPlanApproval: Automatic
      name: ibm-common-service-operator
      source: ibm-operator-catalog
      sourceNamespace: openshift-marketplace